// 問題集の冊子に掲載されているページ一覧（ページ番号とタイトル）
export const PAGES = [
  { number: 3, title: '点図形3' },
  { number: 8, title: 'じゃんけん' },
  { number: 9, title: '図形系列' },
  { number: 11, title: '同図形発見' },
  { number: 12, title: 'シーソー' },
  { number: 14, title: 'お話の内容理解 1' },
  { number: 15, title: 'お話の内容理解 2' },
  { number: 17, title: '分類計数 2' },
  { number: 21, title: '四方からの観察 1' },
  { number: 25, title: 'ききとり練習1' },
  { number: 26, title: 'ききとり練習2' },
  { number: 27, title: '一音一文字' },
  { number: 29, title: '仲間はずれ' },
  { number: 34, title: '関係推理' },
  { number: 35, title: '一対多対応' },
  { number: 37, title: '逆対応' },
  { number: 38, title: '数の構成' },
  { number: 39, title: '線対象' },
  { number: 41, title: '魔法の箱' },
  { number: 42, title: '回転推理' },
  { number: 43, title: 'つりあい' },
  { number: 44, title: '地図上の移動' },
  { number: 45, title: 'ゲームブック' },
  { number: 47, title: '重ね図形' },
  { number: 48, title: 'しりとり 1' },
  { number: 51, title: '重ね点図形' },
  { number: 52, title: '回転図形' },
  { number: 53, title: '常識 1' },
  { number: 54, title: 'りかてきじょうしき1' },
  { number: 55, title: 'りかてきじょうしき2' },
  { number: 56, title: '型押し・転がし図形' },
  { number: 58, title: 'いろいろな移動' },
  { number: 59, title: '条件迷路' },
  { number: 63, title: '数の複合' },
  { number: 64, title: '単位の考え方' },
  { number: 65, title: 'つみ木の数' },
  { number: 74, title: '季節' },
  { number: 79, title: 'ゲームブック 2' },
  { number: 81, title: '鏡映像' },
  { number: 83, title: '３×3方眼上の記憶' },
  { number: 84, title: '仲間あつめ' },
  { number: 85, title: '時の系列' },
  { number: 86, title: '方眼上の位置と移動' },
  { number: 88, title: '立体と展開図' },
  { number: 89, title: '回転 位置 移動' },
  { number: 92, title: '四方からの観察 2' },
  { number: 93, title: '数の総合問題' },
  { number: 94, title: 'しりとり 2' },
  { number: 95, title: '絵と模様の構成' },
  { number: 96, title: '図形分割 2' },
  { number: 97, title: '図形分割 3' },
  { number: 98, title: '図形構成' },
  { number: 99, title: '置き換え' },
  { number: 100, title: '別冊『置き換え・交換・消去』' },
];
